#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    
    #line 1 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
    using NewLife.Model;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    
    #line 2 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Index/_Left_Item.cshtml")]
    public partial class _Areas_Admin_Views_Index__Left_Item_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Index__Left_Item_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
  
    var user = ViewBag.User as IUser ?? User.Identity as IUser;

    var fact = ObjectContainer.Current.Resolve<IMenuFactory>();

    var item = Model as IMenu;
    var childs = fact.GetMySubMenus(item.ID, user).Where(m => m.Visible);
    var url = item.Url.IsNullOrEmpty() ? "" : Url.Content(item.Url);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
 if (childs.Any())
{

            
            #line default
            #line hidden
WriteLiteral("    <li");

WriteLiteral(" class=\"parent\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 437), Tuple.Create("\"", 460)
, Tuple.Create(Tuple.Create("", 445), Tuple.Create("icon", 445), true)
            
            #line 15 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
, Tuple.Create(Tuple.Create(" ", 449), Tuple.Create<System.Object, System.Int32>(item.Icon
            
            #line default
            #line hidden
, 450), false)
);

WriteLiteral("></i><span>");

            
            #line 15 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
                                                    Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</span></a>\r\n        <ul");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n");

            
            #line 17 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
            
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
             foreach (var menu in childs)
            {
                
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
           Write(Html.Partial("_Left_Item", menu));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
                                                 ;
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </li>\r\n");

            
            #line 23 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <li>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 716), Tuple.Create("\"", 727)
            
            #line 27 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
, Tuple.Create(Tuple.Create("", 723), Tuple.Create<System.Object, System.Int32>(url
            
            #line default
            #line hidden
, 723), false)
);

WriteLiteral(" target=\"main\"");

WriteLiteral(">\r\n            <i");

WriteAttribute("class", Tuple.Create(" class=\"", 759), Tuple.Create("\"", 787)
, Tuple.Create(Tuple.Create("", 767), Tuple.Create("icon", 767), true)
, Tuple.Create(Tuple.Create(" ", 771), Tuple.Create("pr-2", 772), true)
            
            #line 28 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
, Tuple.Create(Tuple.Create(" ", 776), Tuple.Create<System.Object, System.Int32>(item.Icon
            
            #line default
            #line hidden
, 777), false)
);

WriteLiteral("></i> ");

            
            #line 28 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
                                            Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </a>\r\n    </li>\r\n");

            
            #line 31 "..\..\Areas\Admin\Views\Index\_Left_Item.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
