#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    
    #line 1 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
    using NewLife.Model;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Index/_Left.cshtml")]
    public partial class _Areas_Admin_Views_Index__Left_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Index__Left_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
  
    var user = ViewBag.User as IUser ?? User.Identity as IUser;

    var fact = ObjectContainer.Current.Resolve<IMenuFactory>();

    var Menus = fact.Root.Childs;
    if (user != null && user.Role != null)
    {
        Menus = fact.GetMySubMenus(fact.Root.ID, user);
    }

    // 如果顶级只有一层，并且至少有三级目录，则提升一级
    if (Menus.Count == 1 && Menus[0].Childs.All(m => m.Childs.Count > 0)) { Menus = Menus[0].Childs; }

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"be-left-sidebar\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"left-sidebar-wrapper\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"left-sidebar-toggle\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">菜单</a>\r\n        <div");

WriteLiteral(" class=\"left-sidebar-spacer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"left-sidebar-scroll\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"left-sidebar-content\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"sidebar-elements\"");

WriteLiteral(">\r\n\r\n");

            
            #line 24 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                         foreach (IMenu menu in Menus.Where(m => m.Visible))
                        {
                            var childs = fact.GetMySubMenus(menu.ID, user).Where(m => m.Visible);


            
            #line default
            #line hidden
WriteLiteral("                            <li ");

            
            #line 28 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                           Write(Html.Raw(menu == Menus[0] ? "class=\"parent active open\"" : ""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 1127), Tuple.Create("\"", 1150)
, Tuple.Create(Tuple.Create("", 1135), Tuple.Create("icon", 1135), true)
            
            #line 29 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
, Tuple.Create(Tuple.Create(" ", 1139), Tuple.Create<System.Object, System.Int32>(menu.Icon
            
            #line default
            #line hidden
, 1140), false)
);

WriteLiteral("></i><span>");

            
            #line 29 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                                                            Write(menu.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</span></a>\r\n");

            
            #line 30 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                 if (childs.Any())
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <ul");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n");

            
            #line 33 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                         foreach (IMenu menu2 in childs)
                                        {
                                            
            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                       Write(Html.Partial("_Left_Item", menu2));

            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                                                              ;
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </ul>\r\n");

            
            #line 38 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </li>\r\n");

            
            #line 40 "..\..\Areas\Admin\Views\Index\_Left.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </ul>\r\n                </div>\r\n            </div>\r\n        " +
"</div>\r\n        <div");

WriteLiteral(" class=\"progress-widget\"");

WriteLiteral(">\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
