#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    
    #line 3 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
    using NewLife.Model;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    
    #line 2 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Index/_Navbar.cshtml")]
    public partial class _Areas_Admin_Views_Index__Navbar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Index__Navbar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
  
    var user = ViewBag.User as IUser ?? User.Identity as IUser;
    var uid = 0;
    var roleNames = "";
    if (user != null)
    {
        uid = user.ID;
        roleNames = user.Roles == null ? "" : user.Roles.Join();
    }
    var cfg = ViewBag.Config as SysConfig;
    var name = cfg == null ? "" : cfg.DisplayName;

    var fact = ObjectContainer.Current.Resolve<IMenuFactory>();
    var Menus = fact.Root.Childs;

            
            #line default
            #line hidden
WriteLiteral("\r\n<nav");

WriteLiteral(" class=\"navbar navbar-expand fixed-top be-top-header\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"be-navbar-header\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"be-toggle-left-sidebar\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon mdi mdi-menu\"");

WriteLiteral("></span></a>\r\n        </div>\r\n");

            
            #line 24 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
        
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
         if (!Menus[0].Name.EqualIgnoreCase("Admin"))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"search-container\"");

WriteLiteral(" style=\"padding-left:0px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"input-group input-group-sm\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"form-control search-input\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"global_txt_search\"");

WriteLiteral(" placeholder=\"查询...\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"global_btn_query\"");

WriteLiteral(">查 询</button>\r\n                    </span>\r\n                </div>\r\n            <" +
"/div>\r\n");

            
            #line 34 "..\..\Areas\Admin\Views\Index\_Navbar.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"be-right-navbar\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav navbar-nav float-right be-user-nav\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"nav-item dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"nav-link dropdown-toggle\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral("> <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1601), Tuple.Create("\"", 1630)
, Tuple.Create(Tuple.Create("", 1607), Tuple.Create<System.Object, System.Int32>(Href("~/Template/img/logo.png")
, 1607), false)
);

WriteLiteral(" /></a>\r\n                    <div");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" role=\"menu\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"user-info\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"user-name\"");

WriteLiteral(">Admin</div>\r\n                        </div>\r\n                        <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" href=\"pages-profile.html\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"icon mdi mdi-face\"");

WriteLiteral("></span>帐号\r\n                        </a><a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon mdi mdi-settings\"");

WriteLiteral("></span>设置</a>\r\n                        <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2155), Tuple.Create("\"", 2181)
, Tuple.Create(Tuple.Create("", 2162), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/User/Logout")
, 2162), false)
);

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"icon mdi mdi-power\"");

WriteLiteral("></span>退出\r\n                        </a>\r\n                    </div>\r\n           " +
"     </li>\r\n            </ul>\r\n            <div");

WriteLiteral(" class=\"page-title\"");

WriteLiteral("></div>\r\n            <ul");

WriteLiteral(" class=\"nav navbar-nav float-right be-icons-nav\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"nav-item dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"nav-link be-toggle-right-sidebar\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon mdi mdi-settings\"");

WriteLiteral("></span>\r\n                    </a>\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"nav-item dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"nav-link dropdown-toggle\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral("><span");

WriteLiteral(" class=\"icon mdi mdi-apps\"");

WriteLiteral("></span></a>\r\n                    <ul");

WriteLiteral(" class=\"dropdown-menu be-connections\"");

WriteLiteral(">\r\n                        <li>\r\n                            <div");

WriteLiteral(" class=\"list\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col\"");

WriteLiteral(">\r\n                                            <a");

WriteLiteral(" class=\"connection-item\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3405), Tuple.Create("\"", 3431)
, Tuple.Create(Tuple.Create("", 3411), Tuple.Create<System.Object, System.Int32>(Href("~/Template/img/1.png")
, 3411), false)
);

WriteLiteral(" /><span>成本系统</span>\r\n                                            </a>\r\n         " +
"                               </div>\r\n                                        <" +
"div");

WriteLiteral(" class=\"col\"");

WriteLiteral(">\r\n                                            <a");

WriteLiteral(" class=\"connection-item\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 3695), Tuple.Create("\"", 3721)
, Tuple.Create(Tuple.Create("", 3701), Tuple.Create<System.Object, System.Int32>(Href("~/Template/img/1.png")
, 3701), false)
);

WriteLiteral(@" /><span>管理后台</span></a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>");

        }
    }
}
#pragma warning restore 1591
