#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Ace_Layout.cshtml")]
    public partial class _Views_Shared__Ace_Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Ace_Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=no\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"author\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n    <title>");

            
            #line 10 "..\..\Views\Shared\_Ace_Layout.cshtml"
      Write(ViewData["Title"]);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 362), Tuple.Create("\"", 427)
, Tuple.Create(Tuple.Create("", 369), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/perfect-scrollbar/css/perfect-scrollbar.css")
, 369), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 459), Tuple.Create("\"", 538)
, Tuple.Create(Tuple.Create("", 466), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/material-design-icons/css/material-design-iconic-font.css")
, 466), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 570), Tuple.Create("\"", 639)
, Tuple.Create(Tuple.Create("", 577), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/datetimepicker/css/bootstrap-datetimepicker.css")
, 577), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 671), Tuple.Create("\"", 724)
, Tuple.Create(Tuple.Create("", 678), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/sweetalert2/sweetalert2.min.css")
, 678), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 756), Tuple.Create("\"", 805)
, Tuple.Create(Tuple.Create("", 763), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/select2/css/select2.min.css")
, 763), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 837), Tuple.Create("\"", 866)
, Tuple.Create(Tuple.Create("", 844), Tuple.Create<System.Object, System.Int32>(Href("~/Template/css/app.css")
, 844), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Views\Shared\_Ace_Layout.cshtml"
Write(RenderSection("css", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 946), Tuple.Create("\"", 983)
, Tuple.Create(Tuple.Create("", 952), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/jquery/jquery.js")
, 952), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1007), Tuple.Create("\"", 1069)
, Tuple.Create(Tuple.Create("", 1013), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/perfect-scrollbar/js/perfect-scrollbar.js")
, 1013), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1093), Tuple.Create("\"", 1151)
, Tuple.Create(Tuple.Create("", 1099), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/bootstrap/dist/js/bootstrap.bundle.js")
, 1099), false)
);

WriteLiteral("></script>\r\n</head>\r\n<body>\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 25 "..\..\Views\Shared\_Ace_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 27 "..\..\Views\Shared\_Ace_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Shared\_Ace_Layout.cshtml"
     if (DbRunTimeModule.Enable)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(" style=\"padding-bottom:45px;\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\Shared\_Ace_Layout.cshtml"
       Write(Html.Raw(DbRunTimeModule.GetInfo()));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 32 "..\..\Views\Shared\_Ace_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1438), Tuple.Create("\"", 1504)
, Tuple.Create(Tuple.Create("", 1444), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/datetimepicker/js/bootstrap-datetimepicker.js")
, 1444), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1528), Tuple.Create("\"", 1608)
, Tuple.Create(Tuple.Create("", 1534), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js")
, 1534), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1632), Tuple.Create("\"", 1658)
, Tuple.Create(Tuple.Create("", 1638), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/app.js")
, 1638), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1682), Tuple.Create("\"", 1723)
, Tuple.Create(Tuple.Create("", 1688), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/prettify/prettify.js")
, 1688), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1747), Tuple.Create("\"", 1802)
, Tuple.Create(Tuple.Create("", 1753), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/sweetalert2/sweetalert2.all.min.js")
, 1753), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1826), Tuple.Create("\"", 1877)
, Tuple.Create(Tuple.Create("", 1832), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/select2/js/select2.full.min.js")
, 1832), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1901), Tuple.Create("\"", 1944)
, Tuple.Create(Tuple.Create("", 1907), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/parsley/parsley.min.js")
, 1907), false)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(document).ready(function () {\r\n            //-initialize the javascr" +
"ipt\r\n            App.init();\r\n\r\n            //$(\'form\').parsley();\r\n            " +
"//Runs prettify\r\n            prettyPrint();\r\n            $(\".datetimepicker\").da" +
"tetimepicker({\r\n                autoclose: true,\r\n                componentIcon:" +
" \'.mdi.mdi-calendar\',\r\n                navIcons: {\r\n                    rightIco" +
"n: \'mdi mdi-chevron-right\',\r\n                    leftIcon: \'mdi mdi-chevron-left" +
"\'\r\n                }\r\n            });\r\n\r\n            //Select2\r\n            $(\"." +
"select2\").select2({\r\n                width: \'50%\',\r\n                placeholder:" +
" \'Select a state\'\r\n            });\r\n\r\n            //Select2 tags\r\n            $(" +
"\".tags\").select2({ tags: true, width: \'100%\' });\r\n\r\n            //根据data-action的" +
"值确定操作类型 action为请求后端执行业务操作，url为直接跳转指定url地址\r\n            //按钮请求action\r\n           " +
" $(document).on(\'click\',\r\n                \'button[data-action=\"action\"], input[d" +
"ata-action=\"action\"], a[data-action=\"action\"]\',\r\n                function (e) {\r" +
"\n                    $this = $(this);\r\n                    //动态设置标签参数\r\n         " +
"           var url = $this.attr(\'href\');\r\n                    var title = $this." +
"attr(\'title\');\r\n                    if (url && url.length > 0) {\r\n              " +
"          $this.data(\'url\', url);\r\n                        //$this.attr(\'href\', " +
"\'javascript:void(0);\');\r\n                    }\r\n\r\n                    //alert(ur" +
"l);\r\n                    var confirm = $this.attr(\'data-confirm\');\r\n            " +
"        var cls = title == \"删除\" ? \"modal-full-color modal-full-color-danger\" : \"" +
"\";\r\n                    swal({\r\n                        title: title,\r\n         " +
"               text: confirm,\r\n                        confirmButtonText: \'确定\',\r" +
"\n                        showCloseButton: true,\r\n                        customC" +
"lass: cls,\r\n                        preConfirm: function () {\r\n                 " +
"           doClickAction($this);\r\n                            return false;\r\n   " +
"                     }\r\n                    });\r\n\r\n                    //阻止按钮本身的" +
"事件冒泡\r\n                    return false;\r\n                });\r\n        });\r\n\r\n\r\n " +
"       function doClickAction($this) {\r\n            var fields = $this.data(\'fie" +
"lds\');\r\n            //参数\r\n            var parameter = \'\';\r\n            if (field" +
"s && fields.length > 0) {\r\n                var fieldArr = fields.split(\',\');\r\n  " +
"              for (var i = 0; i < fieldArr.length; i++) {\r\n                    v" +
"ar detailArr = $(\'[name=\' + fieldArr[i] + \']\');\r\n                    //不对name容器标" +
"签进行限制，直接进行序列化\r\n                    //如果有特殊需求，可以再指定筛选器进行筛选\r\n                    p" +
"arameter += ((parameter.length > 0 ? \'&\' : \'\') + detailArr.serialize());\r\n      " +
"          }\r\n            }\r\n\r\n            //method\r\n            var cmethod = $t" +
"his.data(\'method\');\r\n            var method = \'GET\';\r\n            if (cmethod &&" +
" cmethod.length > 0) {\r\n                method = cmethod;\r\n            }\r\n\r\n    " +
"        //url\r\n            var curl = $this.data(\'url\');\r\n            if (!curl " +
"|| curl.length <= 0) {\r\n                if ($this[0].tagName == \'A\') {\r\n        " +
"            curl = $this.attr(\'href\');\r\n                }\r\n            }\r\n      " +
"      doAction(method, curl, parameter);\r\n        }\r\n\r\n        //ajax请求 methodNa" +
"me 指定GET与POST\r\n        function doAction(methodName, actionUrl, actionParamter) " +
"{\r\n            if (!methodName || methodName.length <= 0 || !actionUrl || action" +
"Url.length <= 0) {\r\n                tips(\'请求参数异常，请保证请求的地址跟参数正确！\', 4, 1000);\r\n   " +
"             return;\r\n            }\r\n\r\n            $.ajax({\r\n                url" +
": actionUrl,\r\n                type: methodName,\r\n                async: false,\r\n" +
"                dataType: \'json\',\r\n                data: actionParamter,\r\n      " +
"          error: function (ex) {\r\n                    tips(\'请求异常！\', 4, 1000);\r\n " +
"                   //console.log(ex);\r\n                },\r\n                befor" +
"eSend: function () {\r\n                    tips(\'正在操作中，请稍候...\', 0, 2000);\r\n      " +
"          },\r\n                success: function (s) {\r\n                    //con" +
"sole.log(s);\r\n                },\r\n                complete: function (result) {\r" +
"\n                    var rs = result.responseJSON;\r\n                    if (rs.d" +
"ata && rs.data.length > 0) {\r\n                        tips(rs.data, 1, 2000);\r\n " +
"                   }\r\n                    if (rs.url && rs.url.length > 0) {\r\n  " +
"                      setTimeout(function () {\r\n                            if (" +
"rs.url == \'[refresh]\') {\r\n                                //刷新页面但不重新加载页面的所有静态资源\r" +
"\n                                location.reload(false);\r\n                      " +
"      } else {\r\n                                window.location.href = rs.url;\r\n" +
"                            }\r\n                        }, 2000);\r\n\r\n            " +
"        }\r\n                }\r\n            });\r\n        }\r\n\r\n        function tip" +
"s(title, index, time) {\r\n            var cls = [\r\n                \"\",\r\n         " +
"       \"modal-full-color modal-full-color-success\",\r\n                \"modal-full" +
"-color modal-full-color-primary\",\r\n                \"modal-full-color modal-full-" +
"color-warning\",\r\n                \"modal-full-color modal-full-color-danger\",\r\n  " +
"              \"modal-full-color modal-full-color-dark\"\r\n            ];\r\n        " +
"    swal({\r\n                position: \'bottom-end\',\r\n                customClass" +
": cls[index],\r\n                title: title,\r\n                showConfirmButton:" +
" false,\r\n                timer: time,\r\n            });\r\n        }\r\n\r\n    </scrip" +
"t>\r\n\r\n");

WriteLiteral("    ");

            
            #line 197 "..\..\Views\Shared\_Ace_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
