#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_DateRange.cshtml")]
    public partial class _Views_Shared__DateRange_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__DateRange_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_DateRange.cshtml"
  
    var formatStr = (Model is String) ? Model : "yyyy-MM-dd";
    var p = ViewBag.Page as Pager;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"dtStart\"");

WriteLiteral(" class=\"control-label mt-1  pr-1 pl-1\"");

WriteLiteral(">时间</label>\r\n    <div");

WriteLiteral(" class=\"input-group date datetimepicker\"");

WriteLiteral(" data-min-view=\"2\"");

WriteLiteral(" data-date-format=\"yyyy-mm-dd\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-group-append\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"btn btn-secondary active\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-th mdi mdi-calendar\"");

WriteLiteral(" style=\"font-size:14px;\"");

WriteLiteral("></i></button>\r\n        </div>\r\n        <input");

WriteLiteral(" class=\"form-control form-control-xs\"");

WriteLiteral(" size=\"14\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 565), Tuple.Create("\"", 586)
            
            #line 11 "..\..\Views\Shared\_DateRange.cshtml"
  , Tuple.Create(Tuple.Create("", 573), Tuple.Create<System.Object, System.Int32>(p["dtStart"]
            
            #line default
            #line hidden
, 573), false)
);

WriteLiteral(" name=\"dtStart\"");

WriteLiteral(" id=\"dtStart\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"dtStart\"");

WriteLiteral(" class=\"control-label mt-1 pr-1 pl-1\"");

WriteLiteral("> 至 </label>\r\n    <div");

WriteLiteral(" class=\"input-group  date datetimepicker\"");

WriteLiteral(" data-min-view=\"2\"");

WriteLiteral(" data-date-format=\"yyyy-mm-dd\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-group-append\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"btn btn-secondary active\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-th mdi mdi-calendar\"");

WriteLiteral(" style=\"font-size:14px;\"");

WriteLiteral("></i></button>\r\n        </div>\r\n        <input");

WriteLiteral(" class=\"form-control form-control-xs\"");

WriteLiteral(" size=\"14\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1098), Tuple.Create("\"", 1117)
            
            #line 20 "..\..\Views\Shared\_DateRange.cshtml"
 , Tuple.Create(Tuple.Create("", 1106), Tuple.Create<System.Object, System.Int32>(p["dtEnd"]
            
            #line default
            #line hidden
, 1106), false)
);

WriteLiteral(" name=\"dtEnd\"");

WriteLiteral(" id=\"dtEnd\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
