#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_Form_Item.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    
    #line 4 "..\..\Views\Shared\_Form_Item.cshtml"
    using NewLife.Cube.Beagle;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 2 "..\..\Views\Shared\_Form_Item.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_Form_Item.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Form_Item.cshtml")]
    public partial class _Views_Shared__Form_Item_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Form_Item_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\_Form_Item.cshtml"
  
    var pair = Model as Pair;
    var entity = pair.First as IEntity;
    var item = pair.Second as FieldItem;

    var err = 0;
    ModelState st = null;
    if (ViewData.ModelState.TryGetValue(item.Name, out st) && st != null) { err = st.Errors.Count; }

    var des = item.Description.TrimStart(item.DisplayName).TrimStart(",", ".", "，", "。");

    var total = 12;
    var label = 3;
    var span = 4;
    if (err == 0 && des.IsNullOrEmpty())
    {
        span = 0;
    }
    else if (item.Type == typeof(Boolean) || item.Type.IsEnum)
    {
        span += 1;
    }
    var input = total - label - span;

            
            #line default
            #line hidden
WriteLiteral("\r\n<label");

WriteLiteral(" class=\"col-12 col-sm-3 col-form-label text-sm-right\"");

WriteLiteral(">");

            
            #line 29 "..\..\Views\Shared\_Form_Item.cshtml"
                                                       Write(item.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n<div");

WriteLiteral(" class=\"col-sm-6 col-lg-6\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 31 "..\..\Views\Shared\_Form_Item.cshtml"
Write(Html.ForEditorX(item, entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</div>\r\n\r\n");

            
            #line 35 "..\..\Views\Shared\_Form_Item.cshtml"
 if (err > 0)
{
    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Shared\_Form_Item.cshtml"
                                                                                                                         
}
else if (!des.IsNullOrEmpty())
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"col-sm-3 col-lg-3\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 42 "..\..\Views\Shared\_Form_Item.cshtml"
   Write(Html.ForDescriptionX(item));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 44 "..\..\Views\Shared\_Form_Item.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
