#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Form_Header.cshtml")]
    public partial class _Views_Shared__Form_Header_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Form_Header_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Form_Header.cshtml"
  
    var msg = ViewBag.StatusMessage as String;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\_Form_Header.cshtml"
 if (!msg.IsNullOrEmpty())
{
    //if (ViewData.ModelState.Values.Any(st => st.Errors.Count > 0))
    if (ViewBag.RowsAffected <= 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"alert alert-success alert-icon alert-icon-border alert-dismissible\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"icon\"");

WriteLiteral("><span");

WriteLiteral(" class=\"mdi mdi-check\"");

WriteLiteral("></span></div>\r\n            <div");

WriteLiteral(" class=\"message\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"mdi mdi-close\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span>\r\n                </button>\r\n");

WriteLiteral("                ");

            
            #line 15 "..\..\Views\Shared\_Form_Header.cshtml"
           Write(msg);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 18 "..\..\Views\Shared\_Form_Header.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"alert alert-danger alert-icon alert-icon-border alert-dismissible\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"icon\"");

WriteLiteral("><span");

WriteLiteral(" class=\"mdi mdi-close-circle-o\"");

WriteLiteral("></span></div>\r\n            <div");

WriteLiteral(" class=\"message\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" class=\"mdi mdi-close\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span></button>\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Shared\_Form_Header.cshtml"
           Write(msg);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 28 "..\..\Views\Shared\_Form_Header.cshtml"
    }
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
