#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=no\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"author\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n    <title>");

            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewData["Title"]);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 370), Tuple.Create("\"", 435)
, Tuple.Create(Tuple.Create("", 377), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/perfect-scrollbar/css/perfect-scrollbar.css")
, 377), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 467), Tuple.Create("\"", 546)
, Tuple.Create(Tuple.Create("", 474), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/material-design-icons/css/material-design-iconic-font.css")
, 474), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 578), Tuple.Create("\"", 631)
, Tuple.Create(Tuple.Create("", 585), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/sweetalert2/sweetalert2.min.css")
, 585), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 663), Tuple.Create("\"", 692)
, Tuple.Create(Tuple.Create("", 670), Tuple.Create<System.Object, System.Int32>(Href("~/Template/css/app.css")
, 670), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("css", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 772), Tuple.Create("\"", 809)
, Tuple.Create(Tuple.Create("", 778), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/jquery/jquery.js")
, 778), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 833), Tuple.Create("\"", 895)
, Tuple.Create(Tuple.Create("", 839), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/perfect-scrollbar/js/perfect-scrollbar.js")
, 839), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 919), Tuple.Create("\"", 977)
, Tuple.Create(Tuple.Create("", 925), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/bootstrap/dist/js/bootstrap.bundle.js")
, 925), false)
);

WriteLiteral("></script>\r\n</head>\r\n<body");

WriteLiteral(" class=\"be-splash-screen\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n   \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1067), Tuple.Create("\"", 1122)
, Tuple.Create(Tuple.Create("", 1073), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/sweetalert2/sweetalert2.all.min.js")
, 1073), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1146), Tuple.Create("\"", 1172)
, Tuple.Create(Tuple.Create("", 1152), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/app.js")
, 1152), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(document).ready(function () {\r\n            //-initialize the javascr" +
"ipt\r\n            App.init();\r\n        });\r\n\r\n    </script>\r\n");

WriteLiteral("    ");

            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
