#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 1 "..\..\Views\Shared\_List_Pager.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_List_Pager.cshtml")]
    public partial class _Views_Shared__List_Pager_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__List_Pager_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\_List_Pager.cshtml"
  
    var page = ViewBag.Page as Pager;
    page.PageUrlTemplate = Url.Action("Index") + "{链接}";
    //page.PageUrlTemplate = page.PageUrlTemplate.Replace("{链接}", Url.Action("Index") + "{链接}");
    // 没有总记录数的时候不显示分页，可以认为不启用分页

    var act = ViewBag.Action as String;
    if (act.IsNullOrEmpty()) { act = Url.Action("Index"); }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Shared\_List_Pager.cshtml"
 if (page.TotalCount > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"dataTables_wrapper row be-datatable-footer fixed-bottom\"");

WriteLiteral(" style=\"padding:5px 15px 0px 15px;\"");

WriteLiteral(">\r\n        <form");

WriteAttribute("action", Tuple.Create(" action=\"", 513), Tuple.Create("\"", 562)
            
            #line 14 "..\..\Views\Shared\_List_Pager.cshtml"
, Tuple.Create(Tuple.Create("", 522), Tuple.Create<System.Object, System.Int32>(act
            
            #line default
            #line hidden
, 522), false)
, Tuple.Create(Tuple.Create("", 526), Tuple.Create("?", 526), true)
            
            #line 14 "..\..\Views\Shared\_List_Pager.cshtml"
, Tuple.Create(Tuple.Create("", 527), Tuple.Create<System.Object, System.Int32>(page.GetBaseUrl(true, true, false)
            
            #line default
            #line hidden
, 527), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-5 mt-2\"");

WriteLiteral(">\r\n                    共 <span>");

            
            #line 17 "..\..\Views\Shared\_List_Pager.cshtml"
                       Write(page.TotalCount.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</span> 条&nbsp;&nbsp;\r\n                    每页 <span>");

            
            #line 18 "..\..\Views\Shared\_List_Pager.cshtml"
                        Write(page.PageSize);

            
            #line default
            #line hidden
WriteLiteral("</span> 条&nbsp;&nbsp;\r\n                    当前第 <span>");

            
            #line 19 "..\..\Views\Shared\_List_Pager.cshtml"
                         Write(page.PageIndex.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</span> 页/共 <span>");

            
            #line 19 "..\..\Views\Shared\_List_Pager.cshtml"
                                                                         Write(page.PageCount.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</span> 页\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-md-7\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"btn-group btn-space mr-2  pull-right\"");

WriteLiteral(" style=\"float:right;\"");

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Views\Shared\_List_Pager.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\_List_Pager.cshtml"
                          
                            int len = 8;
                            int left = (len - 1) / 2, right = len - left - 1;
                            int start = page.PageIndex - left;//开始页数
                            Int64 end = page.PageIndex + right;//结束页数
                            start = start < 1 ? 1 : start;
                            end = end > page.PageCount ? page.PageCount : end;
                            if (page.PageIndex <= 1)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"min-width:32px;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"mdi mdi-skip-previous\"");

WriteLiteral(" style=\"font-weight: bold;font-size: 20px;margin-top:5px;\"");

WriteLiteral("></i></a>\r\n");

WriteLiteral("                                <a");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"min-width:32px;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"mdi mdi-caret-left\"");

WriteLiteral(" style=\"font-weight: bold;font-size: 20px;margin-top:5px;\"");

WriteLiteral("></i></a>\r\n");

            
            #line 34 "..\..\Views\Shared\_List_Pager.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2150), Tuple.Create("\"", 2182)
            
            #line 37 "..\..\Views\Shared\_List_Pager.cshtml"
, Tuple.Create(Tuple.Create("", 2157), Tuple.Create<System.Object, System.Int32>(page.GetPageUrl("首页", 1)
            
            #line default
            #line hidden
, 2157), false)
);

WriteLiteral(" style=\"min-width:32px;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"mdi mdi-skip-previous\"");

WriteLiteral(" style=\"font-weight: bold;font-size: 20px;margin-top:5px;\"");

WriteLiteral("></i></a>\r\n");

WriteLiteral("                                <a");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2369), Tuple.Create("\"", 2417)
            
            #line 38 "..\..\Views\Shared\_List_Pager.cshtml"
, Tuple.Create(Tuple.Create("", 2376), Tuple.Create<System.Object, System.Int32>(page.GetPageUrl("上一页", page.PageIndex-1)
            
            #line default
            #line hidden
, 2376), false)
);

WriteLiteral(" style=\"min-width:32px;\"");

WriteLiteral("><span");

WriteLiteral(" class=\"mdi mdi-caret-left\"");

WriteLiteral(" style=\"font-weight: bold;font-size: 20px;margin-top:5px;\"");

WriteLiteral("></span></a>\r\n");

            
            #line 39 "..\..\Views\Shared\_List_Pager.cshtml"
                            }

                            for (int i = start; i <= end; i++)
                            {
                                if (i == page.PageIndex)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteLiteral(" class=\"btn btn-secondary btn-primary\"");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(">");

            
            #line 45 "..\..\Views\Shared\_List_Pager.cshtml"
                                                                                            Write(i);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 46 "..\..\Views\Shared\_List_Pager.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3045), Tuple.Create("\"", 3085)
            
            #line 49 "..\..\Views\Shared\_List_Pager.cshtml"
, Tuple.Create(Tuple.Create("", 3052), Tuple.Create<System.Object, System.Int32>(page.GetPageUrl(i.ToString(), i)
            
            #line default
            #line hidden
, 3052), false)
);

WriteLiteral(">");

            
            #line 49 "..\..\Views\Shared\_List_Pager.cshtml"
                                                                                                     Write(i);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 50 "..\..\Views\Shared\_List_Pager.cshtml"
                                }
                            }

                            if (page.PageIndex >= page.PageCount)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"min-width:32px;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"mdi mdi-caret-right\"");

WriteLiteral(" style=\"font-weight: bold;font-size: 20px;margin-top:5px;\"");

WriteLiteral("></i></a>\r\n");

WriteLiteral("                                <a");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"min-width:32px;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"mdi mdi-skip-next\"");

WriteLiteral(" style=\"font-weight: bold;font-size: 20px;margin-top:5px;\"");

WriteLiteral("></i></a>\r\n");

            
            #line 57 "..\..\Views\Shared\_List_Pager.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" style=\"min-width:32px;\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3825), Tuple.Create("\"", 3875)
            
            #line 60 "..\..\Views\Shared\_List_Pager.cshtml"
           , Tuple.Create(Tuple.Create("", 3832), Tuple.Create<System.Object, System.Int32>(page.GetPageUrl("下一页", page.PageIndex + 1)
            
            #line default
            #line hidden
, 3832), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"mdi mdi-caret-right\"");

WriteLiteral(" style=\"font-weight: bold;font-size: 20px;margin-top:5px;\"");

WriteLiteral("></i></a>\r\n");

WriteLiteral("                                <a");

WriteLiteral(" class=\"btn btn-secondary\"");

WriteLiteral(" style=\"min-width:32px;\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4060), Tuple.Create("\"", 4105)
            
            #line 61 "..\..\Views\Shared\_List_Pager.cshtml"
           , Tuple.Create(Tuple.Create("", 4067), Tuple.Create<System.Object, System.Int32>(page.GetPageUrl("未页", page.PageCount)
            
            #line default
            #line hidden
, 4067), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"mdi mdi-skip-next\"");

WriteLiteral(" style=\"font-weight: bold;font-size: 20px;margin-top:5px;\"");

WriteLiteral("></i></a>\r\n");

            
            #line 62 "..\..\Views\Shared\_List_Pager.cshtml"
                            }
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                        <select");

WriteLiteral(" id=\"PageSize\"");

WriteLiteral(" name=\"PageSize\"");

WriteLiteral(" onchange=\"$(this).parents(\'form\').submit();\"");

WriteLiteral(" class=\"form-control pagesize\"");

WriteLiteral(" style=\"height:34px;padding:1px;\"");

WriteLiteral(">\r\n                            <option");

WriteLiteral(" value=\"10\"");

WriteLiteral(" ");

            
            #line 65 "..\..\Views\Shared\_List_Pager.cshtml"
                                           Write(page.PageSize == 10 ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">10</option>\r\n                            <option");

WriteLiteral(" value=\"20\"");

WriteLiteral(" ");

            
            #line 66 "..\..\Views\Shared\_List_Pager.cshtml"
                                           Write(page.PageSize == 20 ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">20</option>\r\n                            <option");

WriteLiteral(" value=\"50\"");

WriteLiteral(" ");

            
            #line 67 "..\..\Views\Shared\_List_Pager.cshtml"
                                           Write(page.PageSize == 50 ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">50</option>\r\n                            <option");

WriteLiteral(" value=\"100\"");

WriteLiteral(" ");

            
            #line 68 "..\..\Views\Shared\_List_Pager.cshtml"
                                            Write(page.PageSize == 100 ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">100</option>\r\n                            <option");

WriteLiteral(" value=\"200\"");

WriteLiteral(" ");

            
            #line 69 "..\..\Views\Shared\_List_Pager.cshtml"
                                            Write(page.PageSize == 200 ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">200</option>\r\n                            <option");

WriteLiteral(" value=\"500\"");

WriteLiteral(" ");

            
            #line 70 "..\..\Views\Shared\_List_Pager.cshtml"
                                            Write(page.PageSize == 500 ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">500</option>\r\n                            <option");

WriteLiteral(" value=\"1000\"");

WriteLiteral(" ");

            
            #line 71 "..\..\Views\Shared\_List_Pager.cshtml"
                                             Write(page.PageSize == 1000 ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">1000</option>\r\n                            <option");

WriteLiteral(" value=\"10000\"");

WriteLiteral(" ");

            
            #line 72 "..\..\Views\Shared\_List_Pager.cshtml"
                                              Write(page.PageSize == 10000 ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">10000</option>\r\n                        </select>\r\n                        <scri" +
"pt");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                            $(function () {\r\n                                $" +
"(\'#PageSize\').val(");

            
            #line 76 "..\..\Views\Shared\_List_Pager.cshtml"
                                              Write(page.PageSize);

            
            #line default
            #line hidden
WriteLiteral(");\r\n                            });\r\n                        </script>\r\n         " +
"           </div>\r\n                </div>\r\n            </div>\r\n        </form>\r\n" +
"    </div>\r\n");

            
            #line 84 "..\..\Views\Shared\_List_Pager.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
