#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/_List_Data.cshtml")]
    public partial class _Areas_Admin_Views_User__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<XCode.Membership.UserX>>
    {
        public _Areas_Admin_Views_User__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var set = ViewBag.PageSetting as PageSetting;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
             if (set.EnableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"be-checkbox custom-control custom-checkbox\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" class=\"custom-control-input\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"custom-control-label\"");

WriteLiteral(" for=\"chkAll\"");

WriteLiteral("></label>\r\n                    </div>\r\n                </th>\r\n");

            
            #line 27 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1037), Tuple.Create("\"", 1076)
            
            #line 28 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1044), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 1044), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"名称。登录用户名\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1146), Tuple.Create("\"", 1187)
            
            #line 29 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1153), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Name"))
            
            #line default
            #line hidden
, 1153), false)
);

WriteLiteral(">名称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1240), Tuple.Create("\"", 1288)
            
            #line 30 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1247), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("DisplayName"))
            
            #line default
            #line hidden
, 1247), false)
);

WriteLiteral(">昵称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"性别。未知、男、女\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1359), Tuple.Create("\"", 1399)
            
            #line 31 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1366), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Sex"))
            
            #line default
            #line hidden
, 1366), false)
);

WriteLiteral(">性别</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1452), Tuple.Create("\"", 1493)
            
            #line 32 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1459), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Mail"))
            
            #line default
            #line hidden
, 1459), false)
);

WriteLiteral(">邮件</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1546), Tuple.Create("\"", 1589)
            
            #line 33 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1553), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Mobile"))
            
            #line default
            #line hidden
, 1553), false)
);

WriteLiteral(">手机</a></th>\r\n            ");

WriteLiteral("\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1748), Tuple.Create("\"", 1791)
            
            #line 35 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1755), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("RoleID"))
            
            #line default
            #line hidden
, 1755), false)
);

WriteLiteral(">角色</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1844), Tuple.Create("\"", 1887)
            
            #line 36 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1851), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Online"))
            
            #line default
            #line hidden
, 1851), false)
);

WriteLiteral(">在线</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1940), Tuple.Create("\"", 1983)
            
            #line 37 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1947), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Enable"))
            
            #line default
            #line hidden
, 1947), false)
);

WriteLiteral(">启用</a></th>\r\n            ");

WriteLiteral("\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2163), Tuple.Create("\"", 2209)
            
            #line 39 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2170), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("LastLogin"))
            
            #line default
            #line hidden
, 2170), false)
);

WriteLiteral(">最后登录</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2264), Tuple.Create("\"", 2312)
            
            #line 40 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2271), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("LastLoginIP"))
            
            #line default
            #line hidden
, 2271), false)
);

WriteLiteral(">最后IP</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">日志</th>\r\n");

            
            #line 42 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 42 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:100px;\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 45 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 49 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 49 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
         foreach (var entity in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 52 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 52 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                 if (set.EnableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"be-checkbox custom-control custom-checkbox\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" class=\"custom-control-input\"");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("id", Tuple.Create(" id=\"", 2955), Tuple.Create("\"", 2973)
, Tuple.Create(Tuple.Create("", 2960), Tuple.Create("id_", 2960), true)
            
            #line 56 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
       , Tuple.Create(Tuple.Create("", 2963), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2963), false)
);

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2986), Tuple.Create("\"", 3004)
            
            #line 56 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                      , Tuple.Create(Tuple.Create("", 2994), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2994), false)
);

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"custom-control-label\"");

WriteAttribute("for", Tuple.Create(" for=\"", 3071), Tuple.Create("\"", 3090)
, Tuple.Create(Tuple.Create("", 3077), Tuple.Create("id_", 3077), true)
            
            #line 57 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3080), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 3080), false)
);

WriteLiteral("></label>\r\n                        </div>\r\n                    </td>\r\n");

            
            #line 60 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral(">");

            
            #line 61 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                                                 Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 62 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 63 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 64 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                   Write(entity.Sex);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 65 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.Mail);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 66 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.Mobile);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                ");

WriteLiteral("\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3614), Tuple.Create("\"", 3643)
, Tuple.Create(Tuple.Create("", 3621), Tuple.Create("Role?ID=", 3621), true)
            
            #line 68 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3629), Tuple.Create<System.Object, System.Int32>(entity.RoleID
            
            #line default
            #line hidden
, 3629), false)
);

WriteLiteral(">");

            
            #line 68 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                                Write(entity.RoleName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3736), Tuple.Create("\"", 3795)
, Tuple.Create(Tuple.Create("", 3744), Tuple.Create("mdi", 3744), true)
, Tuple.Create(Tuple.Create(" ", 3747), Tuple.Create("mdi-", 3748), true)
            
            #line 70 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3752), Tuple.Create<System.Object, System.Int32>(entity.Online ? "check" : "minus-circle"
            
            #line default
            #line hidden
, 3752), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 3796), Tuple.Create("\"", 3881)
, Tuple.Create(Tuple.Create("", 3804), Tuple.Create("color:", 3804), true)
            
            #line 70 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                 , Tuple.Create(Tuple.Create(" ", 3810), Tuple.Create<System.Object, System.Int32>(entity.Online ? "green" : "red"
            
            #line default
            #line hidden
, 3811), false)
, Tuple.Create(Tuple.Create("", 3845), Tuple.Create(";", 3845), true)
, Tuple.Create(Tuple.Create(" ", 3846), Tuple.Create("font-weight:", 3847), true)
, Tuple.Create(Tuple.Create(" ", 3859), Tuple.Create("bold;font-size:", 3860), true)
, Tuple.Create(Tuple.Create(" ", 3875), Tuple.Create("17px;", 3876), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3976), Tuple.Create("\"", 4035)
, Tuple.Create(Tuple.Create("", 3984), Tuple.Create("mdi", 3984), true)
, Tuple.Create(Tuple.Create(" ", 3987), Tuple.Create("mdi-", 3988), true)
            
            #line 73 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3992), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "check" : "minus-circle"
            
            #line default
            #line hidden
, 3992), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 4036), Tuple.Create("\"", 4120)
, Tuple.Create(Tuple.Create("", 4044), Tuple.Create("color:", 4044), true)
            
            #line 73 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                 , Tuple.Create(Tuple.Create(" ", 4050), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "green" : "red"
            
            #line default
            #line hidden
, 4051), false)
, Tuple.Create(Tuple.Create("", 4085), Tuple.Create(";font-weight:", 4085), true)
, Tuple.Create(Tuple.Create(" ", 4098), Tuple.Create("bold;font-size:", 4099), true)
, Tuple.Create(Tuple.Create(" ", 4114), Tuple.Create("17px;", 4115), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                ");

WriteLiteral("\r\n                <td>");

            
            #line 76 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.LastLogin.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 4310), Tuple.Create("\"", 4342)
            
            #line 77 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 4318), Tuple.Create<System.Object, System.Int32>(entity.LastLoginAddress
            
            #line default
            #line hidden
, 4318), false)
);

WriteLiteral(">");

            
            #line 77 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                                Write(entity.LastLoginIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 78 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(Html.ActionLink("日志", "Index", "Log", new { UserID = entity.ID }, null));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 79 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 79 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 82 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 84 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 86 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
