#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/Login.cshtml")]
    public partial class _Areas_Admin_Views_User_Login_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_User_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Admin\Views\User\Login.cshtml"
  
    Layout = null;
    ViewBag.Title = "登录";
    var user = ManageProvider.User;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable" +
"=no\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"author\"");

WriteLiteral(" content=\"\"");

WriteLiteral(">\r\n    <title>");

            
            #line 14 "..\..\Areas\Admin\Views\User\Login.cshtml"
      Write(ViewData["Title"]);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 461), Tuple.Create("\"", 526)
, Tuple.Create(Tuple.Create("", 468), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/perfect-scrollbar/css/perfect-scrollbar.css")
, 468), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 558), Tuple.Create("\"", 637)
, Tuple.Create(Tuple.Create("", 565), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/material-design-icons/css/material-design-iconic-font.css")
, 565), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 669), Tuple.Create("\"", 722)
, Tuple.Create(Tuple.Create("", 676), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/sweetalert2/sweetalert2.min.css")
, 676), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 754), Tuple.Create("\"", 783)
, Tuple.Create(Tuple.Create("", 761), Tuple.Create<System.Object, System.Int32>(Href("~/Template/css/app.css")
, 761), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n</head>\r\n<body");

WriteLiteral(" class=\"be-splash-screen\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"be-wrapper be-login\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"be-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"main-content container-fluid\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"splash-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"card card-border-color card-border-color-primary\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"card-header\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" class=\"logo-img\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1209), Tuple.Create("\"", 1238)
, Tuple.Create(Tuple.Create("", 1215), Tuple.Create<System.Object, System.Int32>(Href("~/Template/img/logo.png")
, 1215), false)
);

WriteLiteral(" alt=\"logo\"");

WriteLiteral(">\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"card-body\"");

WriteLiteral(">\r\n");

            
            #line 30 "..\..\Areas\Admin\Views\User\Login.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Admin\Views\User\Login.cshtml"
                             using (Html.BeginForm("Login", "User", new { r = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "" }))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"username\"");

WriteLiteral(" name=\"username\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" placeholder=\"帐号\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\r\n                                </div>\r\n");

WriteLiteral("                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"password\"");

WriteLiteral(" name=\"password\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" placeholder=\"密码\"");

WriteLiteral(">\r\n                                </div>\r\n");

WriteLiteral("                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"be-checkbox custom-control custom-checkbox\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" class=\"custom-control-input\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" id=\"remember\"");

WriteLiteral(" name=\"remember\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" class=\"custom-control-label\"");

WriteLiteral(" for=\"remember\"");

WriteLiteral(">记住密码</label>\r\n                                    </div>\r\n                      " +
"          </div>\r\n");

WriteLiteral("                                <div");

WriteLiteral(" class=\"form-group login-submit\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" class=\"btn btn-primary btn-xl\"");

WriteLiteral(" id=\"btn_login\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">登 录</button>\r\n                                </div>\r\n");

            
            #line 47 "..\..\Areas\Admin\Views\User\Login.cshtml"

                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </div>\r\n                    ");

WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <" +
"script");

WriteAttribute("src", Tuple.Create(" src=\"", 2971), Tuple.Create("\"", 3008)
, Tuple.Create(Tuple.Create("", 2977), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/jquery/jquery.js")
, 2977), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3032), Tuple.Create("\"", 3094)
, Tuple.Create(Tuple.Create("", 3038), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/perfect-scrollbar/js/perfect-scrollbar.js")
, 3038), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3118), Tuple.Create("\"", 3176)
, Tuple.Create(Tuple.Create("", 3124), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/bootstrap/dist/js/bootstrap.bundle.js")
, 3124), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3200), Tuple.Create("\"", 3255)
, Tuple.Create(Tuple.Create("", 3206), Tuple.Create<System.Object, System.Int32>(Href("~/Template/lib/sweetalert2/sweetalert2.all.min.js")
, 3206), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3279), Tuple.Create("\"", 3305)
, Tuple.Create(Tuple.Create("", 3285), Tuple.Create<System.Object, System.Int32>(Href("~/Template/js/app.js")
, 3285), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(document).ready(function () {\r\n            //-initialize the javascr" +
"ipt\r\n            App.init();\r\n        });\r\n    </script>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
